### ISSUE TITLE
[BUG] Initial signature upload lag

### ISSUE THREAD

**Issue by Shadow-230** [goryn-clade/pathfinder#53]
During initial signature paste (when you jump in to new WH and you do initial signature loading to PF using copy paste) there is 10s lag.
Best way to reproduce is to jump to new WH (that was not scanned and has no signatures) and past them there.
![image](https://user-images.githubusercontent.com/79769804/138927629-51108ed7-b6d8-400b-a393-22ff26985704.png)
![image](https://user-images.githubusercontent.com/79769804/138927654-166604a1-7a01-4fee-a599-de1f95508ef2.png)

**Comment by samoneilll** [comment]
I haven't been able to reproduce this issue, but I'll leave it open incase we get more reports.

But what I do know is that when you first paste sigs the signature table goes into a "locked" state until it has finished processing the update. If you try to paste again before it is finished that triggers the "Signature table locked" string to be logged to console. 

I'd be inclined to think that the most obvious explanation is that the application is struggling and just running slowly causing the timeouts and eventual 500, but I think without more data we can't really make that assumption.

**Comment by Shadow-230** [comment]
I think it might be problem with container version. I have extracted php.ini files and changed memory limit and mounted those in docker-compose file and observed performance increase.

**Comment by samoneilll** [comment]
If you're using pathfinder-containers docker-compose then the php.ini should already be in the static/php/ dir and will get mounted in the container from there. I believe it has [256M ](https://github.com/goryn-clade/pathfinder-containers/blob/master/static/php/php.ini) set by default, but if this wasn't enough then let me know.

**Comment by Shadow-230** [comment]
@samoneilll I changed it to 256M in php files and observed performance increase. So the same as default value that you claim that is already configured.

**Comment by cwallace** [comment]
I'm using pathfinder-containers and am also having this issue. Memory is already set to 256M (I didn't change anything from defaults).

https://i.imgur.com/9GRVfHz.png

**Comment by Shadow-230** [comment]
@samoneilll Additional comment. I have changed memory limit for all php config files php.ini and php.ini-production

**Comment by samoneilll** [comment]
@cwallace can you share a little more about what actually happens, and maybe some details about the host machine? no. cores, memory size, etc.

**Comment by cwallace** [comment]
> @cwallace can you share a little more about what actually happens, and maybe some details about the host machine? no. cores, memory size, etc.

My issue may be slightly different than what OP has. The initial signature paste (or any large changes to an existing system) results in a long delay and a [500 error](https://i.imgur.com/7Nt7wPl.png), but wind up posting successfully. The box is a single-core, 1GB RAM "nanode" instance on Linode with only pf installed on it. I don't believe this is a performance issue as we haven't had this problem until v2.1.4 and [resource usage on the box is very low](https://i.imgur.com/vMB97mQ.png).

**Comment by samoneilll** [comment]
@cwallace is there any logging from the pf container about the cause of the 500? you might need to use docker-compose logs to try to find it. Maybe you could also capture some of the network requests? there should in the network panel be requests to the /signature endpoint with POST data that could be interesting to look at.

2.1.4 didn't touch anything related to signature paste. The only changes it made were related to SSO handling.

**Comment by cwallace** [comment]
> 

We're seeing this in the logs every time an error happens:
```
[21-Nov-2021 23:46:30] WARNING: [pool www] child 31322 said into stderr: "Stack trace:"

[21-Nov-2021 23:46:30] WARNING: [pool www] child 31322 said into stderr: "#0 /var/www/html/pathfinder/vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php(72): Monolog\Handler\SocketHandler->writeToSocket('{"task":"logDat...')"

[21-Nov-2021 23:46:30] WARNING: [pool www] child 31322 said into stderr: "#1 /var/www/html/pathfinder/app/Lib/Logging/Handler/SocketHandler.php(58): Monolog\Handler\SocketHandler->write(Array)"

[21-Nov-2021 23:46:30] WARNING: [pool www] child 31322 said into stderr: "#2 /var/www/html/pathfinder/vendor/monolog/monolog/src/Monolog/Handler/Handler.php(27): Exodus4D\Pathfinder\Lib\Logging\Handler\SocketHandler->handle(Array)"

[21-Nov-2021 23:46:30] WARNING: [pool www] child 31322 said into stderr: "#3 /var/www/html/pathfinder/vendor/monolog/monolog/src/Monolog/Handler/BufferHandler.php(99): Monolog\Handler\Handler->handleBatch(Array)"

[21-Nov-2021 23:46:30] WARNING: [pool www] child 31322 said into stderr: "#4 /var/www/html/pathfinder/vendor/monolog/monolog/src/Monolog/Handler/BufferHandler.php(115): Monolog\Handler\BufferHandler->flush()"

[21-Nov-2021 23:46:30] WARNING: [pool www] child 31322 said into stderr: "#5 [internal function]: Monolog\Handler\Buffer..."
```

**Comment by samoneilll** [comment]
@cwallace does the stack-trace go back any further? maybe the response to the request in the browser might have more data. If you just filter the network tab in devTools for "signature" you should hopefully see the 500 response and have a stack-trace in the response.

**Comment by commando29** [comment]
Hi,

Seeing the same issue as @cwallace.  Below is my docker pf log:

2023-01-12 02:21:01,408 INFO reaped unknown pid 2009178

2023-01-12 02:22:01,371 INFO reaped unknown pid 2009262

[12-Jan-2023 02:22:40] WARNING: [pool www] child 2008746 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught RuntimeException: Write timed-out, no data sent for `10` seconds, probably we got disconnected (sent 0 of 675) in /var/www/html/pathfinder/vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php:389"

[12-Jan-2023 02:22:40] WARNING: [pool www] child 2008746 said into stderr: "Stack trace:"

[12-Jan-2023 02:22:40] WARNING: [pool www] child 2008746 said into stderr: "#0 
/var/www/html/pathfinder/vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php(72): Monolog\Handler\SocketHandler->writeToSocket('{"task":"logDat...')"

[12-Jan-2023 02:22:40] WARNING: [pool www] child 2008746 said into stderr: "#1 /var/www/html/pathfinder/app/Lib/Logging/Handler/SocketHandler.php(58): Monolog\Handler\SocketHandler->write(Array)"

[12-Jan-2023 02:22:40] WARNING: [pool www] child 2008746 said into stderr: "#2 
/var/www/html/pathfinder/vendor/monolog/monolog/src/Monolog/Handler/Handler.php(27): Exodus4D\Pathfinder\Lib\Logging\Handler\SocketHandler->handle(Array)"

[12-Jan-2023 02:22:40] WARNING: [pool www] child 2008746 said into stderr: "#3 /var/www/html/pathfinder/vendor/monolog/monolog/src/Monolog/Handler/BufferHandler.php(99): Monolog\Handler\Handler->handleBatch(Array)"

[12-Jan-2023 02:22:40] WARNING: [pool www] child 2008746 said into stderr: "#4 /var/www/html/pathfinder/vendor/monolog/monolog/src/Monolog/Handler/BufferHandler.php(115): Monolog\Handler\BufferHandler->flush()"

[12-Jan-2023 02:22:40] WARNING: [pool www] child 2008746 said into stderr: "#5 [internal function]: Monolog\Handler\Buffer..."

Cheers.

**Comment by commando29** [comment]
I found the problem.  The map setting "Save map changes to log file".  Uncheck that and the problem was solved.

**Comment by samoneilll** [comment]
@commando29  interesting, good catch. I remember I was doing some work on making the logging actually work in docker porperly at some point. I'll have a look into it.

**Comment by TyrHeimdalEVE** [comment]
Adding to milestone, double check permissions and persistence of storage of the logs (they're afaik in file format not in the DB).
